-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.profiles (
  id uuid NOT NULL,
  username text NOT NULL UNIQUE,
  full_name text NOT NULL DEFAULT ''::text,
  role text NOT NULL DEFAULT 'worker'::text CHECK (role = ANY (ARRAY['worker'::text, 'processor'::text, 'admin'::text])),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_login_at timestamp with time zone,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.dispatches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  worker_id uuid,
  worker_username text NOT NULL,
  vehicle_number text NOT NULL,
  material_type text NOT NULL CHECK (material_type = ANY (ARRAY['scrap'::text, 'ferrous'::text, 'non_ferrous'::text, 'other'::text])),
  photo_url text NOT NULL,
  photo_public_id text,
  latitude double precision,
  longitude double precision,
  location_name text,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'submitted'::text CHECK (status = ANY (ARRAY['submitted'::text, 'reviewed'::text, 'approved'::text, 'rejected'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT dispatches_pkey PRIMARY KEY (id),
  CONSTRAINT dispatches_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.owner_stock (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_of_metal text,
  folder_no text,
  folio_number text,
  metal_type text,
  tn_no text,
  paint text,
  drawing_photo_url text,
  drawing_photo_public_id text,
  recorded_time timestamp with time zone,
  metal_photo_url text,
  metal_photo_public_id text,
  amount_purchase numeric,
  processing_start timestamp with time zone,
  processing_end timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT owner_stock_pkey PRIMARY KEY (id)
);
CREATE TABLE public.company_stock (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  metal_type text,
  folder_no text,
  folio_number text,
  drawing_photo_url text,
  drawing_photo_public_id text,
  recorded_time timestamp with time zone,
  processed_metal_type text,
  metal_photo_url text,
  metal_photo_public_id text,
  company_name text,
  product_name text,
  processing_start timestamp with time zone,
  processing_end timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT company_stock_pkey PRIMARY KEY (id)
);
CREATE TABLE public.admin_folders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  folder_type text CHECK (folder_type IS NULL OR (folder_type = ANY (ARRAY['labour'::text, 'with_material'::text, 'general'::text, 'billing'::text]))),
  CONSTRAINT admin_folders_pkey PRIMARY KEY (id)
);
CREATE TABLE public.folder_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  folder_id uuid NOT NULL,
  item_type text NOT NULL,
  item_id uuid NOT NULL,
  position integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT folder_items_pkey PRIMARY KEY (id),
  CONSTRAINT folder_items_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES public.admin_folders(id)
);
CREATE TABLE public.bill_groups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  folder_id uuid,
  name text NOT NULL,
  group_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bill_groups_pkey PRIMARY KEY (id),
  CONSTRAINT bill_groups_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES public.admin_folders(id)
);
CREATE TABLE public.bill_group_photos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bill_group_id uuid NOT NULL,
  photo_url text NOT NULL,
  photo_public_id text,
  position integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bill_group_photos_pkey PRIMARY KEY (id),
  CONSTRAINT bill_group_photos_bill_group_id_fkey FOREIGN KEY (bill_group_id) REFERENCES public.bill_groups(id)
);
CREATE TABLE public.drawing_groups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  folder_id uuid,
  name text NOT NULL,
  group_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT drawing_groups_pkey PRIMARY KEY (id),
  CONSTRAINT drawing_groups_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES public.admin_folders(id)
);
CREATE TABLE public.drawing_group_photos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  drawing_group_id uuid NOT NULL,
  photo_url text NOT NULL,
  photo_public_id text,
  position integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT drawing_group_photos_pkey PRIMARY KEY (id),
  CONSTRAINT drawing_group_photos_drawing_group_id_fkey FOREIGN KEY (drawing_group_id) REFERENCES public.drawing_groups(id)
);
CREATE TABLE public.jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_no text,
  job_type text NOT NULL CHECK (job_type = ANY (ARRAY['labour'::text, 'with_material'::text])),
  job_given_date date,
  po_status text,
  tool_description text,
  tool_part text,
  quantity text,
  expected_completion_date date,
  expected_completion_note text,
  current_machining_status text,
  status text,
  drawing_status text,
  drawing_status_note text,
  model_status text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT jobs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.job_drawings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL,
  file_url text NOT NULL,
  public_id text,
  file_name text,
  file_type text,
  version integer NOT NULL DEFAULT 1,
  is_primary boolean NOT NULL DEFAULT true,
  received_date date,
  notes text,
  uploaded_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT job_drawings_pkey PRIMARY KEY (id),
  CONSTRAINT job_drawings_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT job_drawings_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.job_imports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  file_name text NOT NULL,
  uploaded_by uuid,
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'uploaded'::text,
  total_rows integer NOT NULL DEFAULT 0,
  created_rows integer NOT NULL DEFAULT 0,
  updated_rows integer NOT NULL DEFAULT 0,
  skipped_rows integer NOT NULL DEFAULT 0,
  failed_rows integer NOT NULL DEFAULT 0,
  mapping jsonb,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  folder_id uuid,
  CONSTRAINT job_imports_pkey PRIMARY KEY (id),
  CONSTRAINT job_imports_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id),
  CONSTRAINT job_imports_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES public.admin_folders(id)
);
CREATE TABLE public.job_import_errors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  import_id uuid NOT NULL,
  row_number integer,
  field_name text,
  raw_value text,
  error_message text NOT NULL,
  raw_row jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT job_import_errors_pkey PRIMARY KEY (id),
  CONSTRAINT job_import_errors_import_id_fkey FOREIGN KEY (import_id) REFERENCES public.job_imports(id)
);
CREATE TABLE public.admin_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_id uuid,
  actor_username text,
  action text NOT NULL,
  target_type text NOT NULL,
  target_id uuid,
  detail jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT admin_audit_log_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES auth.users(id)
);
CREATE TABLE public.bill_uploads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  original_filename text NOT NULL,
  base_name text NOT NULL,
  status text NOT NULL DEFAULT 'completed'::text CHECK (status = ANY (ARRAY['uploaded'::text, 'completed'::text, 'failed'::text])),
  original_pdf_path text,
  duplicate_pdf_path text,
  triplicate_pdf_path text,
  invoice_count integer NOT NULL DEFAULT 0 CHECK (invoice_count >= 0),
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bill_uploads_pkey PRIMARY KEY (id),
  CONSTRAINT bill_uploads_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.bills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bill_upload_id uuid NOT NULL,
  sheet_name text NOT NULL,
  invoice_no text,
  invoice_date date,
  our_challan_no text,
  our_challan_date date,
  your_challan_no text,
  your_challan_date date,
  order_no text,
  order_no_label text,
  order_date date,
  eway_bill_no text,
  place_of_supply text,
  state text,
  state_code text,
  transporter_mode text,
  vehicle_number text,
  party_gst_no text,
  party_name text,
  total_quantity numeric,
  amount_before_tax numeric,
  cgst numeric,
  sgst numeric,
  igst numeric,
  total_gst numeric,
  amount_after_tax numeric,
  reverse_charge_gst numeric,
  round_off numeric,
  amount_in_words text,
  job_kind text,
  seller_name text,
  seller_address text,
  bank_details jsonb,
  terms text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  original_pdf_path text,
  duplicate_pdf_path text,
  triplicate_pdf_path text,
  party_address text,
  recipient_label text,
  recipient_note text,
  eway_bill_date date,
  cgst_rate numeric,
  sgst_rate numeric,
  igst_rate numeric,
  seller_descriptor text,
  seller_tax_line text,
  seller_contact text,
  certification text,
  on_behalf_of text,
  signature_designation text,
  receiver_signature text,
  notes_extra text,
  pdf_version integer NOT NULL DEFAULT 1,
  updated_at timestamp with time zone,
  updated_by uuid,
  CONSTRAINT bills_pkey PRIMARY KEY (id),
  CONSTRAINT bills_bill_upload_id_fkey FOREIGN KEY (bill_upload_id) REFERENCES public.bill_uploads(id),
  CONSTRAINT bills_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.bill_line_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bill_id uuid NOT NULL,
  sr_no integer,
  description text,
  hsn_code text,
  uom text,
  quantity numeric,
  rate numeric,
  amount numeric,
  CONSTRAINT bill_line_items_pkey PRIMARY KEY (id),
  CONSTRAINT bill_line_items_bill_id_fkey FOREIGN KEY (bill_id) REFERENCES public.bills(id)
);