// supabase/functions/_selftest/test-copies.ts
//
// Acceptance test for FLEXIBLE COPY HANDLING: a workbook may carry one, two or
// three physical print copies of an invoice, and the output is always all three.
//
// The rule under test, stated once:
//   ONE PHYSICAL INVOICE = ONE BILL RECORD = THREE PRINTABLE COPY PDFs.
//
// So the checks come in three groups.
//
//   A. THE SIX SOURCE SHAPES plus all-three — every combination of which copy
//      blocks the workbook contains must yield one bill carrying all three
//      documents, with the right label on each and identical financial content.
//
//   B. SYNTHESIS FIDELITY — a generated copy must differ from its canonical in
//      the copy label and in nothing else, and must be an independent object:
//      mutating one must not be visible through the others. A shallow clone
//      passes every "identical?" check and still corrupts the second document.
//
//   C. PER-SHEET, NOT PER-WORKBOOK — a workbook mixing a single-copy sheet with a
//      three-copy sheet, and the sheet that arrives with only DUPLICATE or only
//      TRIPLICATE, which is the case a naive "read the ORIGINAL block" parser
//      gets wrong.
//
// Plus the real workbooks: `SAMPLE.xlsx` and the 20-sheet production workbook,
// and the SANITIZED single-copy fixture — generated by `make-fixture.ts` from the
// real acceptance workbook's layout with every identifying value replaced, because
// a customer's name, address, GST numbers and bank account do not belong in a
// repository. Its structure and arithmetic are the real workbook's.
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { readXlsx, textAt, type Sheet } from "../process-bill-upload/_shared/xlsx.ts";
import {
  parseBills,
  parseSheet,
  findCopyBlocks,
  copyDisagreements,
  synthesizeCopy,
  squash,
  COPY_LABEL,
  COPY_ORDER,
  type BillCopy,
  type CopyKind,
} from "../process-bill-upload/_shared/parseBill.ts";
import { renderBillDocument } from "../process-bill-upload/_shared/renderBill.ts";
import { writeXlsx } from "./write-xlsx.ts";

const REPO = resolve(fileURLToPath(new URL(".", import.meta.url)), "../../../..");

let failures = 0;
const check = (ok: boolean, label: string, detail = "") => {
  if (!ok) failures++;
  console.log(`  ${ok ? "PASS" : "FAIL"}  ${label}${detail ? `  ${detail}` : ""}`);
};
const section = (t: string) => console.log(`\n--- ${t} ${"-".repeat(Math.max(0, 62 - t.length))}`);

/* ──────────────────────────────────────────────
   Building the source workbooks

   The fixtures are REAL sheets with their copy blocks relabelled or appended, not
   hand-typed stand-ins: the point is that the parser's own copy detection decides
   what is present, so each fixture has to be an actual invoice whose blocks were
   altered. The base sheet is `test-bills-sanitized.xlsx`, a real invoice layout with
   every identifying value replaced by `_selftest/make-fixture.ts`.
   ────────────────────────────────────────────── */

/**
 * Append a copy of the sheet's ORIGINAL block, marked `kind`, below everything.
 *
 * This is how a two-copy workbook genuinely comes to exist: the author prints the
 * invoice block twice. The cell values are carried over verbatim and only the
 * marker changes, so the added block is a faithful copy of the invoice rather than
 * a second hand-written one — which matters, because the point of the test is that
 * the parser finds and uses whatever copies exist, not that it tolerates two
 * copies that happen to differ.
 */
function withExtraCopy(sheet: Sheet, kind: CopyKind): Sheet {
  /* Copy the sheet's FIRST block whatever it is called, so this also builds the
     DUPLICATE + TRIPLICATE case where the first block is a DUPLICATE. */
  const block = findCopyBlocks(sheet)[0];
  if (!block) throw new Error("fixture: expected a copy block to copy");
  const cells = new Map(sheet.cells);
  const shift = sheet.maxRow + 1;
  for (const cell of sheet.cells.values()) {
    if (cell.row < block.start || cell.row > block.end) continue;
    const moved = { ...cell, row: cell.row + shift };
    /* Retype the marker; everything else is copied unchanged. */
    const value =
      moved.row === block.start + shift && squash(String(cell.value)) === COPY_LABEL[block.kind]
        ? COPY_LABEL[kind]
        : cell.value;
    cells.set(`${moved.row}:${moved.col}`, { ...moved, value });
  }
  return { ...sheet, cells, maxRow: sheet.maxRow + (block.end - block.start + 1) };
}

/**
 * Relabel the sheet's single copy block as `kind`, producing a workbook whose only
 * copy is DUPLICATE or TRIPLICATE.
 *
 * Deleting the ORIGINAL block cannot express this: on a single-copy sheet that block
 * IS the whole sheet, so removing it leaves nothing at all. A workbook that carries
 * only a TRIPLICATE is a real thing an author produces by typing the invoice once and
 * ticking the wrong box — the content is identical, only the marker differs.
 */
function labelledAs(sheet: Sheet, kind: CopyKind): Sheet {
  const block = findCopyBlocks(sheet).find((b) => b.kind === "original");
  if (!block) throw new Error("fixture: expected an ORIGINAL block to relabel");
  const cells = new Map(sheet.cells);
  let renamed = false;
  for (const cell of cells.values()) {
    if (cell.row !== block.start) continue;
    if (squash(String(cell.value)) !== "ORIGINAL") continue;
    cells.set(`${cell.row}:${cell.col}`, { ...cell, value: COPY_LABEL[kind] });
    renamed = true;
  }
  if (!renamed) throw new Error(`fixture: no ORIGINAL marker on row ${block.start + 1}`);
  return { ...sheet, cells };
}

/** The text of a whole rendered PDF, for asserting what was actually printed. */
function pdfText(bytes: Uint8Array): string {
  // Text is drawn as `(literal) Tj`, so the parenthesised runs are the content.
  const raw = new TextDecoder("latin1").decode(bytes);
  const runs = [...raw.matchAll(/\(((?:[^()\\]|\\.)*)\)\s*Tj/g)].map((m) =>
    m[1].replace(/\\([()\\])/g, "$1")
  );
  return runs.join("\n");
}

/** Every array-valued field of a copy, by name. Used for clone independence. */
function arrayFields(copy: BillCopy): Record<string, unknown[]> {
  const out: Record<string, unknown[]> = {};
  for (const [k, v] of Object.entries(copy)) if (Array.isArray(v)) out[k] = v;
  return out;
}

const ALL: CopyKind[] = [...COPY_ORDER];

/* ──────────────────────────────────────────────
   A. All seven source shapes
   ────────────────────────────────────────────── */

section("A. one bill and three documents from every source shape");

/* The single-copy fixture. Sanitized — see the header note — but structurally the
   real thing: one sheet, ORIGINAL only, one invoice, the full reference block, the
   bank block and the four footer rows. */
const single = (await readXlsx(readFileSync(resolve(REPO, "test-bills-sanitized.xlsx")))).sheets[0];
const singleCells = single.cells.size;

/* The fixture's identifying values, so the assertions name them once and a change
   to the generator is a one-line fix here rather than a search. */
const F = {
  invoiceNo: "TEST/001/2026-27",
  orderNo: "TEST/SO/2600001",
  partyChallan: "TEST/OGC/TR/2600001",
  party: "M/s. Sample Traders Ltd.,",
  seller: "EXAMPLE ENGINEERING WORKS",
  qty: 1,
  rate: 9000,
  beforeTax: 9000,
  cgst: 810,
  sgst: 810,
  igst: 0,
  totalGst: 1620,
  afterTax: 10620,
} as const;

/* Each shape is a REAL invoice sheet carrying only the blocks named. A single-copy
   shape is made by relabelling the sheet's one block, since on this sheet the
   ORIGINAL block spans everything. */
const SHAPES: { keep: CopyKind[]; title: string; build: () => Sheet }[] = [
  { keep: ["original"], title: "ORIGINAL only", build: () => single },
  { keep: ["duplicate"], title: "DUPLICATE only", build: () => labelledAs(single, "duplicate") },
  { keep: ["triplicate"], title: "TRIPLICATE only", build: () => labelledAs(single, "triplicate") },
  { keep: ["original", "duplicate"], title: "ORIGINAL + DUPLICATE", build: () => withExtraCopy(single, "duplicate") },
  { keep: ["original", "triplicate"], title: "ORIGINAL + TRIPLICATE", build: () => withExtraCopy(single, "triplicate") },
  {
    keep: ["duplicate", "triplicate"],
    title: "DUPLICATE + TRIPLICATE",
    build: () => withExtraCopy(labelledAs(single, "duplicate"), "triplicate"),
  },
  {
    keep: ALL,
    title: "ORIGINAL + DUPLICATE + TRIPLICATE",
    build: () => withExtraCopy(withExtraCopy(single, "duplicate"), "triplicate"),
  },
];

/* Parsed once here and re-used by group B, so the two groups cannot disagree. */
const parsedByShape = new Map<string, ReturnType<typeof parseSheet>>();

for (const shape of SHAPES) {
  const sheet = shape.build();
  const bill = parseSheet(sheet);
  parsedByShape.set(shape.title, bill);

  const present = findCopyBlocks(sheet).map((b) => b.kind).sort();
  check(
    present.join(",") === [...shape.keep].sort().join(","),
    `${shape.title}: fixture really carries ${present.join(", ") || "(none)"}`,
    present.join(", ")
  );

  /* THE CENTRAL RULE: one worksheet is one bill, never three. */
  check(
    bill.original !== null && bill.duplicate !== null && bill.triplicate !== null,
    `${shape.title}: parse yields all three BillCopy objects`
  );

  /* Canonical selection: ORIGINAL > DUPLICATE > TRIPLICATE. */
  const expectedCanonical = ALL.find((k) => shape.keep.includes(k))!;
  check(
    bill.canonicalKind === expectedCanonical,
    `${shape.title}: canonical is ${COPY_LABEL[expectedCanonical]}`,
    `got ${COPY_LABEL[bill.canonicalKind]}`
  );

  /* `sourceCopies` must describe the WORKBOOK, not the parse result. */
  check(
    bill.sourceCopies.join(",") === [...shape.keep].sort((a, b) => ALL.indexOf(a) - ALL.indexOf(b)).join(","),
    `${shape.title}: sourceCopies reports only what the workbook held`,
    bill.sourceCopies.join(", ")
  );

  /* Every copy carries its own correct output label — the single most visible
     way this feature can go wrong: three PDFs that all say ORIGINAL. */
  for (const kind of ALL) {
    check(
      bill[kind].label === COPY_LABEL[kind] && bill[kind].kind === kind,
      `${shape.title}: ${kind} is labelled ${COPY_LABEL[kind]}`,
      `got "${bill[kind].label}"`
    );
  }

  /* The generated documents must actually SAY it, not just carry it in the model. */
  for (const kind of ALL) {
    const text = pdfText(renderBillDocument([bill[kind]], COPY_LABEL[kind]));
    check(
      new RegExp(`\\b${COPY_LABEL[kind]}\\b`).test(text),
      `${shape.title}: rendered ${kind}.pdf prints ${COPY_LABEL[kind]}`
    );
  }

  /* The financial figures survive whichever copy was the source. */
  const o = bill[expectedCanonical];
  check(
    o.invoiceNo === F.invoiceNo,
    `${shape.title}: invoice number is ${F.invoiceNo}`,
    String(o.invoiceNo)
  );
  check(
    o.amountBeforeTax === F.beforeTax && o.cgst === F.cgst && o.sgst === F.sgst &&
      o.igst === F.igst && o.totalGst === F.totalGst && o.amountAfterTax === F.afterTax,
    `${shape.title}: 9,000 + 1,620 GST = 10,620`,
    `${o.amountBeforeTax} + ${o.cgst}/${o.sgst}/${o.igst} = ${o.amountAfterTax}`
  );
  check(
    o.jobKind === "LABOUR JOB",
    `${shape.title}: job type is LABOUR JOB`,
    String(o.jobKind)
  );
  check(
    o.lineItems.length === 1 && o.lineItems[0].amount === F.rate && o.lineItems[0].rate === F.rate,
    `${shape.title}: the line item survived (1 x 9,000)`
  );
  check(
    o.bankLines.length > 0 && o.termsLines.length > 0 && o.signatureLines.length > 0,
    `${shape.title}: bank, terms and signature blocks survived`,
    `bank=${o.bankLines.length} terms=${o.termsLines.length} sig=${o.signatureLines.length}`
  );
  check(
    o.referenceRows.length > 0,
    `${shape.title}: the reference block (incl. blank rows) survived`,
    `${o.referenceRows.length} rows`
  );
}

/* A DUPLICATE-only or TRIPLICATE-only workbook has no ORIGINAL at all. That is
   the shape a "read the ORIGINAL block" parser gets catastrophically wrong, so
   it is asserted separately and loudly. */
for (const kind of ["duplicate", "triplicate"] as CopyKind[]) {
  const bill = parsedByShape.get(kind === "duplicate" ? "DUPLICATE only" : "TRIPLICATE only")!;
  const blocks = findCopyBlocks(labelledAs(single, kind));
  check(
    blocks.length === 1 && !blocks.some((b) => b.kind === "original"),
    `${COPY_LABEL[kind]}-only: the workbook has no ORIGINAL block at all`
  );
  check(
    bill.original.invoiceNo === F.invoiceNo,
    `${COPY_LABEL[kind]}-only: its data became the ORIGINAL document`
  );
  check(
    bill.original.label === "ORIGINAL",
    `${COPY_LABEL[kind]}-only: the generated original is labelled ORIGINAL, not ${COPY_LABEL[kind]}`
  );
}

/* ──────────────────────────────────────────────
   B. Synthesis fidelity and clone independence
   ────────────────────────────────────────────── */

section("B. a generated copy differs from its canonical only by the label");

/* Which fields are the copy's IDENTITY rather than the invoice's content. The
   designation and its kind are OUTPUT properties — that is the entire intended
   difference. Everything else, including the row span, must match. */
const IDENTITY_FIELDS = new Set<keyof BillCopy>(["kind", "label"]);

for (const shape of SHAPES) {
  const bill = parsedByShape.get(shape.title)!;
  for (const kind of ALL) {
    if (shape.keep.includes(kind)) continue; // a parsed copy is not synthesized
    const canonical = bill[bill.canonicalKind];

    const diffs = (Object.keys(canonical) as (keyof BillCopy)[]).filter(
      (k) => !IDENTITY_FIELDS.has(k) && JSON.stringify(canonical[k]) !== JSON.stringify(bill[kind][k])
    );
    check(
      diffs.length === 0,
      `${shape.title}: generated ${kind} matches ${COPY_LABEL[bill.canonicalKind]} on every other field`,
      diffs.join(", ")
    );

    /* The label really is the only visible difference on the page. Comparing the
       rendered text with the label removed is the check a reviewer would make by
       eye, done mechanically. */
    const strip = (t: string) => t.split("\n").filter((line) => line.trim() !== COPY_LABEL[kind]).join("\n");
    check(
      strip(pdfText(renderBillDocument([bill[kind]], COPY_LABEL[kind]))) ===
        strip(pdfText(renderBillDocument([canonical], COPY_LABEL[kind]))),
      `${shape.title}: generated ${kind}.pdf is identical to the canonical except the label`
    );
  }
}

section("B2. the three copies are independent objects");

/* A shallow `{ ...canonical }` passes every comparison in group B and still shares
   the line-item and bank arrays, so an edit through one document's model would
   silently rewrite the other two. This is the check that fails for a shallow clone.

   Each copy is mutated on its OWN freshly parsed bill: sharing would then be
   indistinguishable from leakage, and the test would pass for the wrong reason. */
{
  const pristine = parsedByShape.get("ORIGINAL only")!;

  for (const kind of ALL) {
    const bill = parseSheet(single);
    const snapshot = new Map(ALL.map((k) => [k, JSON.stringify(bill[k])]));
    const fields = arrayFields(bill[kind]);

    check(
      Object.keys(fields).length >= 8,
      `${kind}: has every array field worth testing for sharing`,
      `${Object.keys(fields).length}: ${Object.keys(fields).join(", ")}`
    );

    /* Push into each array AND into its first object: a clone that copies the
       array but not the elements fails the second half. */
    for (const [name, arr] of Object.entries(fields)) {
      arr.push(`__mutated_${kind}_${name}`);
      const first = arr[0];
      if (first !== null && typeof first === "object") {
        (first as Record<string, unknown>).__mutated = true;
      }
    }

    const alsoMoved = ALL.filter((k) => k !== kind && snapshot.get(k) !== JSON.stringify(bill[k]));
    check(
      alsoMoved.length === 0,
      `${kind}: mutating its arrays and elements left the other two copies byte-identical`,
      alsoMoved.join(", ")
    );
    check(
      snapshot.get(kind) !== JSON.stringify(bill[kind]),
      `${kind}: the mutation really did land on the copy under test`
    );
    check(
      snapshot.get("original") === JSON.stringify(pristine.original),
      `${kind}: the original still equals a freshly parsed one`
    );
  }

  /* Object identity is the actual question: two arrays can compare equal right up
     until one of them changes, so equality alone does not settle sharing. */
  const bill = parseSheet(single);
  const shared: string[] = [];
  for (const [i, a] of ALL.entries()) {
    for (const b of ALL.slice(i + 1)) {
      for (const name of Object.keys(arrayFields(bill[a]))) {
        if (arrayFields(bill[a])[name] === arrayFields(bill[b])[name]) shared.push(`${a}/${b}:${name}`);
      }
    }
  }
  check(shared.length === 0, "no array object is shared between any two copies", shared.join(", "));

  const texts = ALL.map((k) => pdfText(renderBillDocument([bill[k]], COPY_LABEL[k])));
  const bare = (t: string) => t.replace(/\b(ORIGINAL|DUPLICATE|TRIPLICATE)\b/g, "");
  check(
    texts.every((t) => bare(t) === bare(texts[0])),
    "all three documents render identically apart from the copy label"
  );
}

{
  /* `synthesizeCopy` is exported, so its contract is tested directly too: given a
     copy, produce an independent object with the requested identity. */
  const canonical = parsedByShape.get("ORIGINAL only")!.original;
  const clone = synthesizeCopy(canonical, "triplicate");
  check(clone !== canonical, "synthesizeCopy returns a new object");
  check(clone.kind === "triplicate" && clone.label === "TRIPLICATE", "synthesizeCopy stamps the requested identity");
  check(clone.lineItems !== canonical.lineItems, "synthesizeCopy deep-clones lineItems");
  check(
    JSON.stringify({ ...clone, kind: 0, label: 0 }) === JSON.stringify({ ...canonical, kind: 0, label: 0 }),
    "synthesizeCopy is otherwise value-identical"
  );
}

/* ──────────────────────────────────────────────
   C. Per sheet, not per workbook
   ────────────────────────────────────────────── */

section("C. copy presence is decided per SHEET");

/* A real mixed workbook, written out as a real .xlsx and read back through the
   same reader the edge function uses — not a hand-assembled Sheet[]. */
{
  const mixed = writeXlsx([
    { ...single, name: "OnlyOriginal" },
    { ...withExtraCopy(withExtraCopy(single, "duplicate"), "triplicate"), name: "AllThree" },
    { ...labelledAs(single, "duplicate"), name: "OnlyDuplicate" },
  ]);

  const wb = await readXlsx(mixed);
  check(wb.sheets.length === 3, "the mixed workbook really has three sheets", `${wb.sheets.length}`);

  const { bills, skipped } = parseBills(wb.sheets);
  check(skipped.length === 0, "no sheet in the mixed workbook was skipped", skipped.map((s) => s.reason).join("; "));
  check(bills.length === 3, "three sheets -> three bills, not nine", `${bills.length}`);

  const byName = new Map(bills.map((b) => [b.sheetName, b]));
  check(
    byName.get("OnlyOriginal")?.sourceCopies.join(",") === "original",
    "sheet A reports one source copy"
  );
  check(
    byName.get("AllThree")?.sourceCopies.join(",") === "original,duplicate,triplicate",
    "sheet B reports three source copies",
    byName.get("AllThree")?.sourceCopies.join(", ")
  );
  check(
    byName.get("OnlyDuplicate")?.canonicalKind === "duplicate",
    "sheet C takes DUPLICATE as its canonical"
  );

  /* Nine documents, three per bill, and every bill still holds one invoice's
     money — this is the "do not multiply by 3" requirement. */
  const total = bills.reduce((n, b) => n + (b.original.amountAfterTax ?? 0), 0);
  check(
    total === F.afterTax * 3,
    "totals are counted once per bill (3 bills x 10,620)",
    String(total)
  );
  check(
    bills.every((b) => b.original.amountAfterTax === F.afterTax),
    "no bill's total was tripled by generating its copies"
  );

  /* Each copy of a sheet that HAD the block still comes from that block. */
  const allThree = byName.get("AllThree")!;
  check(
    allThree.duplicate.label === "DUPLICATE" && allThree.triplicate.label === "TRIPLICATE",
    "a three-copy sheet keeps its own parsed blocks, not clones"
  );

  /* The aggregate documents: one page per recognised sheet, in worksheet order,
     which is what the workbook-level PDFs are. */
  for (const kind of ALL) {
    const bytes = renderBillDocument(bills.map((b) => b[kind]), COPY_LABEL[kind]);
    const pages = (new TextDecoder("latin1").decode(bytes).match(/\/Type\s*\/Page[^s]/g) ?? []).length;
    check(pages === 3, `aggregate ${kind}.pdf has one page per sheet (3)`, `${pages}`);
  }
}

/* ──────────────────────────────────────────────
   D. Rejection still happens for a sheet with NO copy at all
   ────────────────────────────────────────────── */

section("D. a sheet with no recognisable copy is still rejected");

{
  const noCopy: Sheet = { ...single, cells: new Map(), maxRow: 0, maxCol: 0 };
  // Keep some invoice-ish text so the failure can only be about the missing copy.
  for (const cell of single.cells.values()) {
    if (cell.row < 20) noCopy.cells.set(`${cell.row}:${cell.col}`, cell);
  }
  let message = "";
  try {
    parseSheet(noCopy);
  } catch (err) {
    message = err instanceof Error ? err.message : String(err);
  }
  check(message !== "", "a sheet with no ORIGINAL/DUPLICATE/TRIPLICATE is rejected");
  check(
    message.includes("No ORIGINAL, DUPLICATE or TRIPLICATE invoice copy was found"),
    "the error says which copy was missing",
    message.split(".")[1]?.trim() ?? message
  );
  check(
    !/missing (DUPLICATE|TRIPLICATE)/.test(message),
    "the error no longer blames a merely-absent copy"
  );
}

/* A sheet that is not an invoice at all is still skipped, not crashed on. */
{
  const junk: Sheet = { name: "Notes", cells: new Map(), maxRow: 2, maxCol: 2 };
  junk.cells.set("0:0", { row: 0, col: 0, type: "inline", value: "Shopping list" });
  junk.cells.set("1:0", { row: 1, col: 0, type: "inline", value: "Milk" });
  const { bills, skipped } = parseBills([junk, single]);
  check(bills.length === 1, "a non-invoice sheet is skipped, the real one still parses", `${bills.length}`);
  check(
    skipped.length === 1 && skipped[0].sheetName === "Notes",
    "the non-invoice sheet is reported as skipped",
    skipped.map((s) => s.sheetName).join(", ")
  );
}

/* ──────────────────────────────────────────────
   E. The real workbooks
   ────────────────────────────────────────────── */

section("E. the fixture workbook and the real workbooks");

/* E1 — the single-copy fixture: one sheet, ORIGINAL only, no real business data. */
{
  const wb = await readXlsx(readFileSync(resolve(REPO, "test-bills-sanitized.xlsx")));
  check(wb.sheets.length === 1, "the sanitized fixture has exactly one sheet", `${wb.sheets.length}`);
  check(
    findCopyBlocks(wb.sheets[0]).length === 1,
    "the sanitized fixture carries exactly one copy block"
  );
  check(
    findCopyBlocks(wb.sheets[0])[0].kind === "original",
    "that one block is ORIGINAL — no DUPLICATE and no TRIPLICATE in the file"
  );

  /* No real business data may reach the repository through this fixture. This is
     asserted rather than trusted, because the generator is hand-edited and a
     pasted-back real value would otherwise slip in unnoticed. */
  const allText = [...wb.sheets[0].cells.values()].map((c) => String(c.value)).join("\n");
  const forbidden: [string, RegExp][] = [
    ["seller name", /SAASTHA/i],
    ["recipient name", /Hawkins/i],
    ["seller GSTIN", /27AAMPE1857D2ZT/],
    ["recipient GSTIN", /27AAACH1784M1Z9/],
    ["MSME id", /UDYAM-MH-33-0054711/],
    ["e-mail address", /saastha(01|enggworks2011)@/i],
    ["phone number", /9969434432|9969142688/],
    ["bank name", /FEDERAL BANK/i],
    ["account number", /17750200004019/],
    ["IFSC", /FDRL0001775/],
    ["vehicle number", /JQ\s*4172/i],
    ["invoice number", /SEW\/317/],
    ["order number", /WT\/SO\/2602879/],
    ["challan number", /WT\/OGC\/TR\/261199/],
  ];
  for (const [what, re] of forbidden) {
    check(!re.test(allText), `fixture carries no real ${what}`);
  }

  const { bills, skipped } = parseBills(wb.sheets);
  check(bills.length === 1, "the sanitized fixture -> 1 bill", `${bills.length}`);
  check(skipped.length === 0, "nothing was skipped", JSON.stringify(skipped));
  check(skipped.length === 0 && bills[0].canonicalKind === "original", "its canonical is ORIGINAL");
  check(bills[0].sourceCopies.join(",") === "original", "its sourceCopies is [original]");

  const o = bills[0].original;
  check(o.invoiceNo === F.invoiceNo, `invoice ${F.invoiceNo}`, String(o.invoiceNo));
  check(o.invoiceDate === "2026-09-28", "invoice date 28/09/2026", String(o.invoiceDate));
  check(o.orderNo === F.orderNo, `service order ${F.orderNo}`, String(o.orderNo));
  check(o.yourChallanNo === F.partyChallan, `recipient challan ${F.partyChallan}`, String(o.yourChallanNo));
  check(o.partyName === F.party, `recipient ${F.party}`, String(o.partyName));
  check(o.sellerName === F.seller, `seller ${F.seller}`, String(o.sellerName));
  check(o.partyAddress.length === 3, "the recipient address kept its three lines", `${o.partyAddress.length}`);
  check(o.jobKind === "LABOUR JOB", "job type LABOUR JOB", String(o.jobKind));
  check(o.totalQuantity === F.qty, `quantity ${F.qty}`, String(o.totalQuantity));
  check(o.lineItems[0].rate === F.rate, `rate ${F.rate}`, String(o.lineItems[0].rate));
  check(o.amountBeforeTax === F.beforeTax, `before tax ${F.beforeTax}`, String(o.amountBeforeTax));
  check(
    o.cgst === F.cgst && o.sgst === F.sgst && o.igst === F.igst,
    "CGST 810, SGST 810, IGST 0",
    `${o.cgst}/${o.sgst}/${o.igst}`
  );
  check(o.totalGst === F.totalGst, `total GST ${F.totalGst}`, String(o.totalGst));
  check(o.amountAfterTax === F.afterTax, `total after tax ${F.afterTax}`, String(o.amountAfterTax));
  check(o.roundOff === 0 || o.roundOff === null, "round off blank/zero", String(o.roundOff));
  /* The rates are stored as PERCENTAGES: the source prints the fraction 0.09. */
  check(o.cgstRate === 9 && o.sgstRate === 9 && o.igstRate === 18, "tax rates 9/9/18 percent", `${o.cgstRate}/${o.sgstRate}/${o.igstRate}`);
  check(o.ewayBillNo === null, "the blank e-way row is kept as a row with a null value", String(o.ewayBillNo));

  /* The decoy sentence. Its presence is the reason matching must stay exact. */
  const decoy = [...single.cells.values()].some((c) =>
    /Original Copy of Invoice for Receipt/i.test(String(c.value))
  );
  check(decoy, "the fixture really does contain the decoy sentence about all three copies");
  check(
    findCopyBlocks(single).length === 1,
    "the decoy sentence did not register as DUPLICATE and TRIPLICATE",
    `${findCopyBlocks(single).length} block(s)`
  );
  check(
    bills[0].duplicate.label === "DUPLICATE" && bills[0].triplicate.label === "TRIPLICATE",
    "the two generated copies are labelled from the sheet name, not the prose"
  );

  /* Three documents, one page each, each labelled. */
  for (const kind of ALL) {
    const bytes = renderBillDocument([bills[0][kind]], COPY_LABEL[kind]);
    const pages = (new TextDecoder("latin1").decode(bytes).match(/\/Type\s*\/Page[^s]/g) ?? []).length;
    const text = pdfText(bytes);
    check(pages === 1, `${kind}.pdf is exactly one invoice page`, `${pages} page(s)`);
    check(text.includes("10,620.00"), `${kind}.pdf shows 10,620.00`);
    check(text.includes("LABOUR JOB"), `${kind}.pdf shows LABOUR JOB`);
    check(new RegExp(`\\b${COPY_LABEL[kind]}\\b`).test(text), `${kind}.pdf prints ${COPY_LABEL[kind]}`);
  }
  check(copyDisagreements(bills[0]).length === 0, "a one-copy sheet reports no disagreements to review");
  check(singleCells > 0, "the fixture sheet is non-empty", `${singleCells} cells`);
}

/* E2 — SAMPLE.xlsx, the existing three-copy workbook: no regression. */
{
  const wb = await readXlsx(readFileSync(resolve(REPO, "SAMPLE.xlsx")));
  const { bills, skipped } = parseBills(wb.sheets);
  check(bills.length === 2, "SAMPLE.xlsx still parses 2 bills", `${bills.length}`);
  check(skipped.length === 0, "SAMPLE.xlsx skips nothing", JSON.stringify(skipped));
  check(
    bills.every((b) => b.sourceCopies.length === 3),
    "both SAMPLE sheets still carry all three source copies",
    bills.map((b) => b.sourceCopies.length).join(", ")
  );
  check(
    bills.every((b) => b.canonicalKind === "original"),
    "both SAMPLE sheets are still canonicalised on ORIGINAL"
  );
  for (const b of bills) {
    check(
      copyDisagreements(b).length === 0,
      `SAMPLE sheet "${b.sheetName}": its three source copies still agree`,
      JSON.stringify(copyDisagreements(b))
    );
    for (const kind of ALL) {
      check(b[kind].label === COPY_LABEL[kind], `SAMPLE "${b.sheetName}": ${kind} label intact`);
    }
  }
}

/* E3 — the 20-sheet production workbook: the change must not disturb it. */
{
  const wb = await readXlsx(readFileSync(resolve(REPO, "BILL 301 TO.xlsx")));
  const { bills, skipped } = parseBills(wb.sheets);
  check(bills.length === 20, "BILL 301 TO.xlsx still parses 20 bills", `${bills.length}`);
  check(skipped.length === 0, "20 sheets, none skipped", JSON.stringify(skipped));
  check(
    bills.every((b) => b.sourceCopies.length === 3),
    "every production sheet still carries three source copies"
  );
  /* Sheet 320's ORIGINAL writes a challan number its other copies leave blank.
     That inconsistency must still be REPORTED, not silenced by the new code. */
  const s320 = bills.find((b) => /320/.test(b.sheetName));
  const d320 = s320 ? copyDisagreements(s320) : [];
  check(
    d320.some((d) => d.field === "yourChallanNo" && d.original === "abc"),
    "sheet 320's source inconsistency is still reported",
    JSON.stringify(d320)
  );
  check(
    bills.filter((b) => copyDisagreements(b).length > 0).length === 1,
    "only that one sheet disagrees"
  );
}

/* An EMPTY `sourceCopies` is impossible for a parsed bill — it would mean a bill
   was accepted without a canonical, which is the one thing the rule forbids. */
section("F. invariants across every bill parsed above");
{
  const everything = parseBills(
    (await readXlsx(readFileSync(resolve(REPO, "BILL 301 TO.xlsx")))).sheets
  ).bills;
  check(
    everything.every((b) => b.sourceCopies.length >= 1),
    "no bill was accepted without at least one source copy"
  );
  check(
    everything.every((b) => b.sourceCopies.includes(b.canonicalKind)),
    "every bill's canonical is one of its own source copies"
  );
  check(
    everything.every((b) => ALL.every((k) => b[k] && b[k].label === COPY_LABEL[k])),
    "every bill carries all three correctly-labelled copies"
  );
  /* The line-item table is per INVOICE, so the three copies must agree on it
     even when two of them are clones — a copy that lost its lines would print a
     total with no rows above it. */
  check(
    everything.every((b) => b.duplicate.lineItems.length === b.original.lineItems.length &&
      b.triplicate.lineItems.length === b.original.lineItems.length),
    "no copy lost its line items"
  );
  const rows = everything.reduce(
    (n, b) => n + b.original.lineItems.length,
    0
  );
  check(rows > 0, "line items were actually present to compare", `${rows} rows`);
  check(textAt(single, 1, 1) === "ORIGINAL", "the ORIGINAL label sits at B2 in the source", textAt(single, 1, 1));
}

console.log(
  failures === 0
    ? "\nCOPY-FLEXIBILITY CHECKS: all passed."
    : `\nCOPY-FLEXIBILITY CHECKS: ${failures} failure(s).`
);
if (failures > 0) process.exitCode = 1;